[package]
name = "wordle"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = {version = "0.12.9", features = ["json"]}
text-to-ascii-art = "0.1.5"
